apiVersion: v1
kind: Service
metadata:
  name: web-chat-service
spec:
  type: NodePort
  selector:
    app: web-chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31002